services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./sql/migrations:/migrations
    command: ["-path", "/migrations", "-database", "mysql://root:root@tcp(mysql:3306)/orders", "up"]
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure